// api
export const GET_COMMENT_OF_POST_SUCCESS: string = 'GET_COMMENT_OF_POST_SUCCESS'
export const GET_COMMENT_OF_POST_FAILED: string = 'GET_COMMENT_OF_POST_FAILED'

export const ADD_COMMENT_SUCCESS: string = 'ADD_COMMENT_SUCCESS'
export const ADD_COMMENT_FAILED: string = 'ADD_COMMENT_FAILED'
